"""Compute-God Python runtime.

This module exposes a minimal framework inspired by the README. It provides the
basic pieces required to declare a universe of rules and iteratively search for
fixpoints under a user supplied metric.
"""

from .rule import Rule, rule
from .universe import God, Universe
from .engine import fixpoint, FixpointResult
from .observer import Observer, ObserverEvent
from .miyu import MiyuBond, bond_miyu
from .bingzi import Bingzi, Pingzi, peculiar_asymmetry, qianli_bingfeng, 冰子, 千里冰封, 瓶子
from .jizi import Jizi, ThermalDual, Zijiji, thermal_dual, 机子, 子机机, 热对偶, 自机子对偶
from .bingzi import (
    Bingzi,
    Pingzi,
    PingziRelation,
    peculiar_asymmetry,
    qianli_bingfeng,
    冰子,
    千里冰封,
    瓶子,
    平子,
)
from .sanzi import Sanzi, SanziOverview, Weizi, 三子, 维子
from .siqianzi import (
    Siqianzi,
    SiqianziDualEdge,
    SiqianziDualNode,
    SiqianziThermalNetwork,
    thermal_dual_network,
    死前子,
    死前子节点,
    死前子连线,
    死前子网络,
    死前子热对偶网络,
)
from .jiahao import (
    JiahaoMaximumThermalDual,
    jiahao_max_thermal_dual,
    jiahao_max_thermal_dual_from_network,
    嘉豪最大热对偶,
)
from .yihong import YihongMiyuThermalDual, yihong_miyu_thermal_dual, 一弘美羽热对偶
from .jiaose import ChromaticDual, Jiaozi, Sezi, chromatic_dual, 角子, 色子, 色角对偶
from .august import EndlessAugust
from .abura_soba import (
    AburaSobaProfile,
    NoodleCanvas,
    OilLayer,
    TareBlend,
    Topping,
    assemble_abura_soba,
    油そば,
)
from .entangle import (
    Chanzi,
    Entangler,
    EntanglementSnapshot,
    Jiuzi,
    纠子,
    缠子,
    纠缠子,
)
from .anti_quantum import (
    AntiQuantumAlgorithm,
    AntiQuantumDual,
    QuantumAttackSurface,
    anti_quantum_dual,
    抗量子算法,
    抗量子对偶,
    量子攻击面,
)
from .existence import ExistenceWitness, StabilityWitness, 存在子, 稳定子
from .ctc import ClosedTimelikeCurve, CTCOptimisationResult, optimise_closed_timelike_curve
from .threshold import ThresholdSpace, ThresholdOptimisationResult, optimise_threshold_space
from .life import (
    LifeLattice,
    LifeOptimisationResult,
    optimise_game_of_life,
    optimise_game_of_life_multistep,
)
from .rule_optimisation import RuleOptimisationResult, optimise_rule_weights
from .degree_space import DegreeDual, DegreeSpace, DegreeTensor, tensor_product
from .metaverse import (
    MetaverseBlueprint,
    bond_metaverse_with_love,
    ideal_metaverse_universe,
    metaverse_metric,
    run_ideal_metaverse,
)
from .mihoyo import (
    MihoyoStudioBlueprint,
    MiyuCreativeProfile,
    MiyuJoinsMihoyoResult,
    bond_miyu_with_mihoyo,
    mihoyo_alignment_metric,
    measure_mihoyo_fengshui,
    mihoyo_progress_metric,
    miyu_join_mihoyo_universe,
    run_miyu_join_mihoyo,
)
from .meta_spacetime import (
    MetaSpacetimeBlueprint,
    ideal_meta_spacetime_universe,
    meta_spacetime_metric,
    run_meta_spacetime,
)
from .complex_dynamics import (
    ComplexDynamicsBlueprint,
    complex_dynamics_metric,
    design_complex_dynamics_universe,
    run_complex_dynamics,
)
from .complex_network import (
    ComplexNetworkBlueprint,
    complex_network_metric,
    ideal_complex_network_universe,
    run_complex_network,
)
from .llm_cooperation import (
    DEFAULT_LLM_COOPERATION,
    LLMAgentContribution,
    LLMCooperationBlueprint,
    ideal_llm_cooperation_universe,
    llm_cooperation_blueprint_from_agents,
    llm_cooperation_metric,
    run_llm_cooperation,
)
from .everything_demonstration import (
    EverythingDemonstrationBlueprint,
    physical_everything_demonstration_universe,
    physical_everything_metric,
    run_physical_everything_demonstration,
)
from .drug_lab import (
    DrugLabOptimisationResult,
    drug_lab_metric,
    ideal_drug_lab_universe,
    run_drug_lab,
)
from .tianhe import TianheLine, 天和线
from .catalysis import (
    CatalysisOutcome,
    Chanzi,
    Jiuzi,
    catalyse_jiuzi_and_chanzi,
)
from .theorem import (
    InferenceRule,
    Proof,
    ProofStep,
    modus_ponens,
    reconstruct_proof,
    run_theorem_prover,
    theorem_metric,
    theorem_proving_universe,
)
from .elf_usdt import (
    ELFUSDTMarket,
    SwapDirection,
    SwapEvent,
    ELF,
    USDT,
    精灵,
    泰达,
)
from .adhd import (
    ADHDProfile,
    ADHDResponse,
    CoefficientOfEngagement,
    StimulusProfile,
    simulate_coe,
)
from .logic import Feizi, Ouzi, Ruofei, 非子, 欧子, 若非
from .shengbing import ConceptCongruence, 生病全等于放屁
from .utawarerumono import LegendChant, Utawarerumono, UtawarerumonoChant, 传颂之物
from .love_wishing_machine import (
    WishParameters,
    love_wishing_fixpoint,
    love_wishing_map,
    love_wishing_metric,
    love_wishing_rule,
    love_wishing_universe,
    wish_granted,
)
from .courtship_cohomology import (
    CochainSpace,
    CourtshipCochainComplex,
    CourtshipDifferential,
    courtship_cohomology_story,
)
from .world import WorldExecutionRequest, world_execute
from .shuangxiang import (
    BiphasicOptimisationResult,
    BiphasicState,
    continue_biphasic_descent,
    optimise_biphasic_state,
    双相,
    双相梯度下降,
    继续梯度下降,
)

__all__ = [
    "Rule",
    "rule",
    "God",
    "Universe",
    "fixpoint",
    "FixpointResult",
    "Observer",
    "ObserverEvent",
    "MiyuBond",
    "bond_miyu",
    "EndlessAugust",
    "Bingzi",
    "Pingzi",
    "PingziRelation",
    "peculiar_asymmetry",
    "qianli_bingfeng",
    "冰子",
    "千里冰封",
    "瓶子",
    "Sanzi",
    "SanziOverview",
    "Weizi",
    "Siqianzi",
    "SiqianziDualNode",
    "SiqianziDualEdge",
    "SiqianziThermalNetwork",
    "thermal_dual_network",
    "JiahaoMaximumThermalDual",
    "jiahao_max_thermal_dual",
    "jiahao_max_thermal_dual_from_network",
    "YihongMiyuThermalDual",
    "yihong_miyu_thermal_dual",
    "Jiaozi",
    "Sezi",
    "ChromaticDual",
    "chromatic_dual",
    "角子",
    "色子",
    "色角对偶",
    "Jizi",
    "Zijiji",
    "ThermalDual",
    "thermal_dual",
    "机子",
    "子机机",
    "热对偶",
    "自机子对偶",
    "三子",
    "维子",
    "平子",
    "死前子",
    "死前子节点",
    "死前子连线",
    "死前子网络",
    "死前子热对偶网络",
    "嘉豪最大热对偶",
    "一弘美羽热对偶",
    "AburaSobaProfile",
    "NoodleCanvas",
    "OilLayer",
    "TareBlend",
    "Topping",
    "assemble_abura_soba",
    "油そば",
    "AntiQuantumAlgorithm",
    "AntiQuantumDual",
    "QuantumAttackSurface",
    "anti_quantum_dual",
    "抗量子算法",
    "量子攻击面",
    "抗量子对偶",
    "Jiuzi",
    "Chanzi",
    "Entangler",
    "EntanglementSnapshot",
    "纠子",
    "缠子",
    "纠缠子",
    "ExistenceWitness",
    "StabilityWitness",
    "存在子",
    "稳定子",
    "WishParameters",
    "love_wishing_fixpoint",
    "love_wishing_map",
    "love_wishing_metric",
    "love_wishing_rule",
    "love_wishing_universe",
    "wish_granted",
    "CochainSpace",
    "CourtshipCochainComplex",
    "CourtshipDifferential",
    "courtship_cohomology_story",
    "ClosedTimelikeCurve",
    "CTCOptimisationResult",
    "optimise_closed_timelike_curve",
    "ThresholdSpace",
    "ThresholdOptimisationResult",
    "optimise_threshold_space",
    "LifeLattice",
    "LifeOptimisationResult",
    "optimise_game_of_life",
    "optimise_game_of_life_multistep",
    "RuleOptimisationResult",
    "optimise_rule_weights",
    "DegreeSpace",
    "DegreeDual",
    "DegreeTensor",
    "tensor_product",
    "MetaverseBlueprint",
    "bond_metaverse_with_love",
    "ideal_metaverse_universe",
    "metaverse_metric",
    "run_ideal_metaverse",
    "MihoyoStudioBlueprint",
    "MiyuCreativeProfile",
    "MiyuJoinsMihoyoResult",
    "bond_miyu_with_mihoyo",
    "mihoyo_alignment_metric",
    "measure_mihoyo_fengshui",
    "mihoyo_progress_metric",
    "miyu_join_mihoyo_universe",
    "run_miyu_join_mihoyo",
    "MetaSpacetimeBlueprint",
    "ideal_meta_spacetime_universe",
    "meta_spacetime_metric",
    "run_meta_spacetime",
    "ComplexDynamicsBlueprint",
    "complex_dynamics_metric",
    "design_complex_dynamics_universe",
    "run_complex_dynamics",
    "ComplexNetworkBlueprint",
    "complex_network_metric",
    "ideal_complex_network_universe",
    "run_complex_network",
    "LLMAgentContribution",
    "LLMCooperationBlueprint",
    "DEFAULT_LLM_COOPERATION",
    "ideal_llm_cooperation_universe",
    "llm_cooperation_blueprint_from_agents",
    "llm_cooperation_metric",
    "run_llm_cooperation",
    "EverythingDemonstrationBlueprint",
    "physical_everything_demonstration_universe",
    "physical_everything_metric",
    "run_physical_everything_demonstration",
    "DrugLabOptimisationResult",
    "drug_lab_metric",
    "ideal_drug_lab_universe",
    "run_drug_lab",
    "TianheLine",
    "天和线",
    "Jiuzi",
    "Chanzi",
    "CatalysisOutcome",
    "catalyse_jiuzi_and_chanzi",
    "InferenceRule",
    "Proof",
    "ProofStep",
    "modus_ponens",
    "reconstruct_proof",
    "run_theorem_prover",
    "theorem_metric",
    "theorem_proving_universe",
    "ELFUSDTMarket",
    "SwapDirection",
    "SwapEvent",
    "ELF",
    "USDT",
    "精灵",
    "泰达",
    "StimulusProfile",
    "ADHDResponse",
    "ADHDProfile",
    "CoefficientOfEngagement",
    "simulate_coe",
    "Feizi",
    "Ouzi",
    "Ruofei",
    "ConceptCongruence",
    "非子",
    "欧子",
    "若非",
    "生病全等于放屁",
    "Utawarerumono",
    "UtawarerumonoChant",
    "LegendChant",
    "传颂之物",
    "WorldExecutionRequest",
    "world_execute",
    "BiphasicState",
    "BiphasicOptimisationResult",
    "continue_biphasic_descent",
    "optimise_biphasic_state",
    "双相",
    "双相梯度下降",
    "继续梯度下降",
]
